"""empty message

Revision ID: 7b4294b6d216
Revises: 
Create Date: 2021-08-05 23:54:13.248116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4294b6d216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_type', sa.String(length=15), nullable=True),
    sa.Column('source_ipv4', sa.Text(), nullable=True),
    sa.Column('destination_ipv4', sa.Text(), nullable=True),
    sa.Column('octet_delta_count', sa.Integer(), nullable=True),
    sa.Column('packet_delta_count', sa.Integer(), nullable=True),
    sa.Column('flow_start', sa.DateTime(), nullable=True),
    sa.Column('flow_end', sa.DateTime(), nullable=True),
    sa.Column('source_transport_port', sa.Integer(), nullable=True),
    sa.Column('destination_transport_port', sa.Integer(), nullable=True),
    sa.Column('ingress_interface', sa.Integer(), nullable=True),
    sa.Column('egress_interface', sa.Integer(), nullable=True),
    sa.Column('layer_2_segment_id', sa.Integer(), nullable=True),
    sa.Column('protocol_identifier', sa.String(), nullable=True),
    sa.Column('flow_end_reason', sa.Integer(), nullable=True),
    sa.Column('tcp_control_bits', sa.String(), nullable=True),
    sa.Column('ip_class_of_service', sa.Integer(), nullable=True),
    sa.Column('maximum_ttl', sa.Integer(), nullable=True),
    sa.Column('flow_direction', sa.Integer(), nullable=True),
    sa.Column('ingress_interface_attr', sa.Integer(), nullable=True),
    sa.Column('egress_interface_attr', sa.Integer(), nullable=True),
    sa.Column('vxlan_export_role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
